In [4]:
import numpy as np

In [5]:
a = np.array([1, 2, 3])

In [6]:
a

array([1, 2, 3])

In [7]:
a[1]

2

In [8]:
a = np.array([[1, 2, 3],[4, 5, 6]])

In [9]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a[0]

array([1, 2, 3])

In [11]:
a[1]

array([4, 5, 6])

In [12]:
a[0][0]

1

In [13]:
a.shape

(2, 3)

In [14]:
# 次元
a.ndim

2

In [15]:
a.dtype.name

'int64'

In [16]:
a.size

6

In [17]:
# 0〜30までの間で、5飛びで配列を作ってくれる
np.arange(0, 30, 5)

array([ 0,  5, 10, 15, 20, 25])

In [18]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [19]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.zeros((3, 4), dtype=np.int16)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [21]:
np.ones((3, 4), dtype=np.int16)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [22]:
[np.nan] * 10

[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]

In [23]:
# 0〜2の間で等間隔に、9つ数値配列を作成してくれる
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [24]:
a = np.arange(6)

In [25]:
a

array([0, 1, 2, 3, 4, 5])

In [26]:
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [27]:
np.arange(10000)

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [28]:
np.arange(10000).reshape(100,100)

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [29]:
np.set_printoptions(threshold=10000)
np.arange(10000).reshape(100,100)

, 7064, 7065,
        7066, 7067, 7068, 7069, 7070, 7071, 7072, 7073, 7074, 7075, 7076,
        7077, 7078, 7079, 7080, 7081, 7082, 7083, 7084, 7085, 7086, 7087,
        7088, 7089, 7090, 7091, 7092, 7093, 7094, 7095, 7096, 7097, 7098,
        7099],
       [7100, 7101, 7102, 7103, 7104, 7105, 7106, 7107, 7108, 7109, 7110,
        7111, 7112, 7113, 7114, 7115, 7116, 7117, 7118, 7119, 7120, 7121,
        7122, 7123, 7124, 7125, 7126, 7127, 7128, 7129, 7130, 7131, 7132,
        7133, 7134, 7135, 7136, 7137, 7138, 7139, 7140, 7141, 7142, 7143,
        7144, 7145, 7146, 7147, 7148, 7149, 7150, 7151, 7152, 7153, 7154,
        7155, 7156, 7157, 7158, 7159, 7160, 7161, 7162, 7163, 7164, 7165,
        7166, 7167, 7168, 7169, 7170, 7171, 7172, 7173, 7174, 7175, 7176,
        7177, 7178, 7179, 7180, 7181, 7182, 7183, 7184, 7185, 7186, 7187,
        7188, 7189, 7190, 7191, 7192, 7193, 7194, 7195, 7196, 7197, 7198,
        7199],
       [7200, 7201, 7202, 7203, 7204, 7205, 7206, 7207, 7208, 7209, 

In [30]:
x = np.arange(0, 10, 2)
y = np.arange(5)
z = np.arange(0, 100, 20)

In [31]:
x

array([0, 2, 4, 6, 8])

In [32]:
y

array([0, 1, 2, 3, 4])

In [33]:
z

array([ 0, 20, 40, 60, 80])

In [34]:
np.append(x, y)

array([0, 2, 4, 6, 8, 0, 1, 2, 3, 4])

In [35]:
# vertical
np.vstack([x, y, z])

array([[ 0,  2,  4,  6,  8],
       [ 0,  1,  2,  3,  4],
       [ 0, 20, 40, 60, 80]])

In [36]:
# horizontal
np.hstack([x, y, z])

array([ 0,  2,  4,  6,  8,  0,  1,  2,  3,  4,  0, 20, 40, 60, 80])

In [37]:
a = np.array([10, 20, 30, 40 ,50])

In [38]:
b = np.arange(5)

In [39]:
a

array([10, 20, 30, 40, 50])

In [40]:
b

array([0, 1, 2, 3, 4])

In [41]:
a - b

array([10, 19, 28, 37, 46])

In [42]:
b - a

array([-10, -19, -28, -37, -46])

In [43]:
b * 2

array([0, 2, 4, 6, 8])

In [44]:
a < 30

array([ True,  True, False, False, False])

In [45]:
a = np.ones((2,3))

In [46]:
a *= 3

In [47]:
a

array([[3., 3., 3.],
       [3., 3., 3.]])

In [48]:
a = np.random.random((2, 3))
a

array([[0.32194337, 0.2156848 , 0.65518425],
       [0.23034067, 0.20844514, 0.88458484]])

In [49]:
a.sum()

2.516183076505581

In [50]:
a.min()

0.20844514198020447

In [51]:
a.max()

0.884584838313813

In [52]:
# 平均
a.mean()

0.41936384608426347

In [53]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
# 横の計算
a.sum(axis=1)

array([ 6, 22, 38])

In [55]:
# 縦の計算
a.sum(axis=0)

array([12, 15, 18, 21])

In [56]:
# 転置
a.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [57]:
a.resize((2, 6))

In [58]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [59]:
import matplotlib.pyplot as plt

In [60]:
%matplotlib inline

In [61]:
v = np.random.normal(2, 0.5, 10000)

In [66]:
v

74430822, 2.99773832, 1.87822315,
       2.10115083, 1.59698502, 2.24815352, 1.36029345, 2.45447798,
       1.5404245 , 1.99072957, 2.2907298 , 1.77715108, 2.00905437,
       2.4847667 , 1.93070046, 1.90466055, 1.41961073, 1.68764354,
       1.66660146, 1.9260635 , 2.21230157, 2.0397284 , 2.39541249,
       1.73469931, 1.54908495, 1.15428692, 1.75444869, 1.83530003,
       1.52064116, 1.4787798 , 3.18922975, 1.78663585, 2.15445947,
       1.96135809, 1.70871559, 2.40566292, 1.87692795, 3.23522228,
       2.00373788, 1.69576119, 2.30810198, 3.20745538, 1.3905611 ,
       2.11252366, 1.81995597, 2.0601831 , 1.923898  , 2.41735301,
       1.64283314, 1.3406588 , 2.17767026, 2.26837773, 1.93835496,
       2.26327503, 2.05116464, 1.31234144, 2.62139537, 1.56131354,
       2.5142875 , 1.27684325, 1.92825351, 2.31399587, 2.08240426,
       1.50700358, 2.62119602, 1.91926124, 2.05520646, 1.92384511,
       2.29759742, 1.3756691 , 1.75031737, 1.869566  , 1.81483622,
       1.25741112, 2.2331521

In [69]:
plt.hist(v, bins=50)

AttributeError: 'Rectangle' object has no property 'normed'